server:
  port: 40000
spring:
  application:
    name: price-analyzer
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: exaone3.5:2.4b
      embedding:
        model: bge-m3
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        allow-empty-collection: true
        collection-name: products
        use-tls: false
        initialize-schema: true

